### ISSUE TITLE
[feature request] Add "Controlnet" to Model Change Device Repeaters Node

### ISSUE THREAD

**Issue by MoonMoon82** [longgui0318/comfyui-mask-util#3]
Especially some controlnet models for SDXl are huge! 
Could you also please add "controlnet" model input to the Model Change Device Repeaters node?

BTW: This node is really really awesome!!!

Kind regards

**Comment by longgui0318** [comment]
OK, I will add it over the weekend.

**Comment by longgui0318** [comment]
Done, but I only conducted a simple test. Detailed testing for features like the ip_adapter has not been done yet.
